services:
  web: 
    image: nginx
    volumes:
      - ./servidor-web:/usr/share/nginx/html
    ports:
      - 8080:80

  db:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1